### ISSUE TITLE
The repository structure doesn't correspond to imports inside proto files ("third_party/googleapis/" part is missing in paths)

### ISSUE THREAD

**Issue by mmarinchenko** [yandex-cloud/cloudapi#1]
Hi, guys!

I guess the title says it all. Plugins for code generation expect valid directory structure. For example you may read about this [here](https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md) (see _ProtoRoot_).

Because of wrong directory structure this repository cannot be just linked as git submodule to other repository. It requires manual path modification.

**Comment by baranov1ch** [comment]
Hi, thanks for the feedback :)

Unfortunately we haven't tested yet integration with this plugin. The current directory structure works for python, java-maven (probably with some tweaks) and golang (which requires special magic anyway).

Hope we'll look more closely into the issue soon

**Comment by mmarinchenko** [comment]
Ok I see) Thanks for the quick response!

Another issue I faced with this plugin is common output directory setting. So when used the generated C# class for yandex/api/operation.proto is overwritten by generated class for yandex/cloud/operation/operation.proto :)

This is not your fault of course but it would be nice to avoid the same naming for different objects even in different namespaces. Not just because of this plugin but also for better code readability.

Otherwise, everything seems to be worked as expected. Cool!)

**Comment by mmarinchenko** [comment]
For those who may be interested I leave here a VS 2017 project configuration sample showing how to compile YC API protos in C#.

[YandexCloud.API.txt](https://github.com/yandex-cloud/cloudapi/files/3313264/YandexCloud.API.txt)

**Comment by mmarinchenko** [comment]
It seems the `ProtoRoot` can contain multiple directories separated by semicolon (see [comment](https://github.com/yandex-cloud/cloudapi/issues/4#issuecomment-565532226) at issue #4).

**Comment by mmarinchenko** [comment]
[YandexCloud.API (new).txt](https://github.com/yandex-cloud/cloudapi/files/3964969/YandexCloud.API.new.txt)

Updated VS 2017 project configuration sample showing how to compile YC API protos in C# based on the info from ussie #4.
