### ISSUE TITLE
DNS resolution failed for service: stt.api.cloud.yandex-cloud.net:443

### ISSUE THREAD

**Issue by 12E6FD9** [yandex-cloud/cloudapi#11]
I'm following [this example](https://cloud.yandex.ru/docs/speechkit/stt/api/streaming-examples) and it was fine till today. Now I get DNS error. Any ideas how it can be fixed? 

`<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for service: stt.api.cloud.yandex-cloud.net:443"
	debug_error_string = "
{
    "created": "@1642795937.739745884",
    "description": "Resolver transient failure",
    "file": "src/core/ext/filters/client_channel/client_channel.cc",
    "file_line": 1324,
    "referenced_errors": [
        {
            "created": "@1642795937.739740447",
            "description": "DNS resolution failed for service: stt.api.cloud.yandex-cloud.net:443",
            "file": "src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc",
            "file_line": 359,
            "grpc_status": 14,
            "referenced_errors": [
                {
                    "created": "@1642795937.739600798",
                    "description": "C-ares status is not ARES_SUCCESS qtype=A name=stt.api.cloud.yandex-cloud.net is_balancer=0: Domain name not found",
                    "file": "src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc",
                    "file_line": 698,
                    "referenced_errors": [
                        {
                            "created": "@1642795937.739131933",
                            "description": "C-ares status is not ARES_SUCCESS qtype=AAAA name=stt.api.cloud.yandex-cloud.net is_balancer=0: Domain name not found",
                            "file": "src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc",
                            "file_line": 698
                        }
                    ]
                }
            ]
        }
    ]
}"
`

**Comment by GennadySpb** [comment]
Hi there!
Domain name should be `stt.api.cloud.yandex.net` (not `stt.api.cloud.yandex-cloud.net`).

**Comment by 12E6FD9** [comment]
thanks a lot!
