### ISSUE TITLE
Error in streaming recognition for Turkish

### ISSUE THREAD

**Issue by kfmn** [yandex-cloud/cloudapi#13]
I am testing a streaming recognition for Turkish.
I set model as "regular:rc" and language_code as "tr-TR"
When sending recognition request I receive an exception grpc._channel._Rendezvous and no recognition results is returned.
If I replace language_code with en-US the recognition works somehow and no exception is thrown.
Is tr-TR indeed supported in regular:rc model?

**Comment by MAnyKey** [comment]
I'd suggest getting in touch with the technical support [here](https://console.cloud.yandex.ru/support/create-ticket)
