### ISSUE TITLE
YandexGPT: Missing foundation_models_service.proto

### ISSUE THREAD

**Issue by tyumentsev4** [yandex-cloud/cloudapi#20]
why was the `yandex/cloud/ai/foundation_models/v1/foundation_models_service.proto` [deleted](https://github.com/yandex-cloud/cloudapi/commit/390160c557e592a05781d9120e7eb7079089f9d5)

**Comment by akarimova** [comment]
Thank you for the report! 
We've fixed the issue.

**Comment by opportunity356** [comment]
[fixed](https://github.com/yandex-cloud/cloudapi/commit/cddb306d05ba399789f11312082c681edada4e6d)
